name: Lint Code

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
env:
  DATABASE_URL: ${{ secrets.MEGALAN_PIPELINE_DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.MEGALAN_PIPELINE_NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.MEGALAN_PIPELINE_NEXTAUTH_URL }}
  DISCORD_CLIENT_ID: ${{ secrets.MEGALAN_PIPELINE_DISCORD_CLIENT_ID }}
  DISCORD_CLIENT_SECRET: ${{ secrets.MEGALAN_PIPELINE_DISCORD_CLIENT_SECRET }}
  OSU_CLIENT_ID: ${{ secrets.MEGALAN_PIPELINE_OSU_CLIENT_ID }}
  OSU_CLIENT_SECRET: ${{ secrets.MEGALAN_PIPELINE_OSU_CLIENT_SECRET }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.5.0

    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      run: |
        npm run lint
