name: Lint Code

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.5.0

    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      run: npm run lint

    # more steps here:
