name: Lint Code

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.5.0

    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      run: |
        npm run lint
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
        OSU_CLIENT_ID: ${{ secrets.OSU_CLIENT_ID }}
        OSU_CLIENT_SECRET: ${{ secrets.OSU_CLIENT_SECRET }}
